spring:
    datasource:
        username: admin
        password: 123
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:mydb
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show_sql: true
        properties.hibernate.format_sql: true
        hibernate.ddl.auto: update
    h2:
        console.enabled: true
        console.path: /h2